---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: a serverless implementation of the unix command wc

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wc
      Runtime: go1.x
      CodeUri: wc.zip
      Description: counts words
      Timeout: 15
      Role:
        Fn::GetAtt: Role.Arn
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: POST
        Lines:
          Type: Api
          Properties:
            Path: /lines
            Method: POST
        Words:
          Type: Api
          Properties:
            Path: /words
            Method: POST

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ['lambda.amazonaws.com']
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  Endpoint:
    Description: the api endpoint
    Value:
      Fn::Sub: 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

